<?php

namespace CodersLabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findStartingWhit($startString){
        return $this->getEntityManager()->createQuery(
                'SELECT u FROM CodersLabBundle:User u WHERE u.nick LIKE :startStr'
            )
            ->setParameter("startStr", $startString."%")
            ->getResult();
    }
}
