security:
    firewalls:
        secured_area:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            anonymous: ~
            http_basic: ~
                

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            users:
                dominik:  { password: dominik, roles: 'ROLE_USER' }
                admin: { password: admin, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext